# vim: syntax=python
env = Environment()

cmd = "xxdata_11.for xxrptn.for i4unit.for i4fctn.for xxword.for xxcase.for xfelem.for xxslen.for"

f2py_builder = Builder(action='f2py -c $SOURCE ' + cmd)
env.Append(BUILDERS={'F2py': f2py_builder})

env.F2py('xxdata_11.so', 'xxdata_11.pyf')
install = env.Install('..', source='xxdata_11.so')

env.Default(install)
