# vim: syntax=python
env = Environment()

sources = ['xxdata_11.for', 'xxrptn.for', 'i4unit.for', 'i4fctn.for',
    'xxword.for', 'xxcase.for', 'xfelem.for', 'xxslen.for']

sources += [ '../xxdata_11.pyf', '../helper_functions.for' ]

f2py_builder = Builder(action='f2py -m _xxdata_11 -c $SOURCES')
env.Append(BUILDERS={'F2py': f2py_builder})

shared_object = '../../_xxdata_11.so'
env.F2py(shared_object, source=sources)
env.Install('../../atomic', source=shared_object)
